build:
	gcc -Wall -Wextra -pedantic -std=c11 -pthread molecules-pt1.c -o molecules-pt1
	gcc -Wall -Wextra -pedantic -std=c11 -pthread molecules-pt2.c -o molecules-pt2

clean:
	rm -f molecules-pt1 molecules-pt2
